# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Will LSM\Desktop\Microscope Software\LS_Pycro_App\LS_Pycro_App\views\ui_files\AcqOrderDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AcqOrderDialog(object):
    def setupUi(self, AcqOrderDialog):
        AcqOrderDialog.setObjectName("AcqOrderDialog")
        AcqOrderDialog.resize(532, 172)
        AcqOrderDialog.setInputMethodHints(QtCore.Qt.ImhNone)
        self.yes_button = QtWidgets.QPushButton(AcqOrderDialog)
        self.yes_button.setGeometry(QtCore.QRect(170, 140, 75, 23))
        self.yes_button.setObjectName("yes_button")
        self.cancel_button = QtWidgets.QPushButton(AcqOrderDialog)
        self.cancel_button.setGeometry(QtCore.QRect(270, 140, 75, 23))
        self.cancel_button.setObjectName("cancel_button")
        self.order_text_browser = QtWidgets.QTextBrowser(AcqOrderDialog)
        self.order_text_browser.setGeometry(QtCore.QRect(10, 10, 511, 121))
        self.order_text_browser.setObjectName("order_text_browser")

        self.retranslateUi(AcqOrderDialog)
        QtCore.QMetaObject.connectSlotsByName(AcqOrderDialog)

    def retranslateUi(self, AcqOrderDialog):
        _translate = QtCore.QCoreApplication.translate
        AcqOrderDialog.setWindowTitle(_translate("AcqOrderDialog", "Acquisition Order"))
        self.yes_button.setText(_translate("AcqOrderDialog", "Yes"))
        self.cancel_button.setText(_translate("AcqOrderDialog", "Cancel"))
        self.order_text_browser.setHtml(_translate("AcqOrderDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Are you sure you want to change this?</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">If set to TIME_SAMP, all samples set in the regions setup will be acquired at each timepoint. This is the default setting.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">If set to SAMP_TIME, a full time series will be performed for each fish set in the regions setup.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">If set to POS_TIME, a full time series will be performed for each region set in the regions setup.</span></p></body></html>"))
