# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Raghu\Desktop\Microscope Software\LS_Pycro_App\LS_Pycro_App\hardware\pump_and_rotation\views\ui\PumpAndRotationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PumpAndRotationDialog(object):
    def setupUi(self, PumpAndRotationDialog):
        PumpAndRotationDialog.setObjectName("PumpAndRotationDialog")
        PumpAndRotationDialog.resize(494, 194)
        self.gridLayout = QtWidgets.QGridLayout(PumpAndRotationDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.velocity_line_edit = QtWidgets.QLineEdit(PumpAndRotationDialog)
        self.velocity_line_edit.setObjectName("velocity_line_edit")
        self.gridLayout.addWidget(self.velocity_line_edit, 1, 1, 1, 1)
        self.velocity_label = QtWidgets.QLabel(PumpAndRotationDialog)
        self.velocity_label.setObjectName("velocity_label")
        self.gridLayout.addWidget(self.velocity_label, 1, 0, 1, 1)
        self.one_step_f_button = QtWidgets.QPushButton(PumpAndRotationDialog)
        self.one_step_f_button.setObjectName("one_step_f_button")
        self.gridLayout.addWidget(self.one_step_f_button, 1, 3, 1, 1)
        self.stop_button = QtWidgets.QPushButton(PumpAndRotationDialog)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout.addWidget(self.stop_button, 3, 1, 1, 1)
        self.rotation_label = QtWidgets.QLabel(PumpAndRotationDialog)
        self.rotation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rotation_label.setObjectName("rotation_label")
        self.gridLayout.addWidget(self.rotation_label, 0, 3, 1, 1)
        self.max_button = QtWidgets.QPushButton(PumpAndRotationDialog)
        self.max_button.setObjectName("max_button")
        self.gridLayout.addWidget(self.max_button, 2, 1, 1, 1)
        self.zero_button = QtWidgets.QPushButton(PumpAndRotationDialog)
        self.zero_button.setObjectName("zero_button")
        self.gridLayout.addWidget(self.zero_button, 4, 1, 1, 1)
        self.one_step_b_button = QtWidgets.QPushButton(PumpAndRotationDialog)
        self.one_step_b_button.setObjectName("one_step_b_button")
        self.gridLayout.addWidget(self.one_step_b_button, 2, 3, 1, 1)
        self.pump_label = QtWidgets.QLabel(PumpAndRotationDialog)
        self.pump_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pump_label.setObjectName("pump_label")
        self.gridLayout.addWidget(self.pump_label, 0, 1, 1, 1)
        self.steps_line_edit = QtWidgets.QLineEdit(PumpAndRotationDialog)
        self.steps_line_edit.setObjectName("steps_line_edit")
        self.gridLayout.addWidget(self.steps_line_edit, 6, 3, 1, 1)
        self.steps_label = QtWidgets.QLabel(PumpAndRotationDialog)
        self.steps_label.setObjectName("steps_label")
        self.gridLayout.addWidget(self.steps_label, 6, 2, 1, 1)
        self.f_button = QtWidgets.QPushButton(PumpAndRotationDialog)
        self.f_button.setObjectName("f_button")
        self.gridLayout.addWidget(self.f_button, 3, 3, 1, 1)
        self.b_button = QtWidgets.QPushButton(PumpAndRotationDialog)
        self.b_button.setObjectName("b_button")
        self.gridLayout.addWidget(self.b_button, 4, 3, 1, 1)
        self.port_combo_box = QtWidgets.QComboBox(PumpAndRotationDialog)
        self.port_combo_box.setObjectName("port_combo_box")
        self.port_combo_box.addItem("")
        self.port_combo_box.addItem("")
        self.port_combo_box.addItem("")
        self.gridLayout.addWidget(self.port_combo_box, 6, 1, 1, 1)
        self.port_label = QtWidgets.QLabel(PumpAndRotationDialog)
        self.port_label.setObjectName("port_label")
        self.gridLayout.addWidget(self.port_label, 6, 0, 1, 1)

        self.retranslateUi(PumpAndRotationDialog)
        QtCore.QMetaObject.connectSlotsByName(PumpAndRotationDialog)

    def retranslateUi(self, PumpAndRotationDialog):
        _translate = QtCore.QCoreApplication.translate
        PumpAndRotationDialog.setWindowTitle(_translate("PumpAndRotationDialog", "Dialog"))
        self.velocity_label.setText(_translate("PumpAndRotationDialog", "Velocity"))
        self.one_step_f_button.setText(_translate("PumpAndRotationDialog", "One Step Forward"))
        self.stop_button.setText(_translate("PumpAndRotationDialog", "Stop"))
        self.rotation_label.setText(_translate("PumpAndRotationDialog", "Rotation"))
        self.max_button.setText(_translate("PumpAndRotationDialog", "Max"))
        self.zero_button.setText(_translate("PumpAndRotationDialog", "Zero"))
        self.one_step_b_button.setText(_translate("PumpAndRotationDialog", "One Step Backward"))
        self.pump_label.setText(_translate("PumpAndRotationDialog", "Pump"))
        self.steps_label.setText(_translate("PumpAndRotationDialog", "Steps"))
        self.f_button.setText(_translate("PumpAndRotationDialog", "Forward"))
        self.b_button.setText(_translate("PumpAndRotationDialog", "Backward"))
        self.port_combo_box.setItemText(0, _translate("PumpAndRotationDialog", "I"))
        self.port_combo_box.setItemText(1, _translate("PumpAndRotationDialog", "E"))
        self.port_combo_box.setItemText(2, _translate("PumpAndRotationDialog", "O"))
        self.port_label.setText(_translate("PumpAndRotationDialog", "Port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PumpAndRotationDialog = QtWidgets.QDialog()
    ui = Ui_PumpAndRotationDialog()
    ui.setupUi(PumpAndRotationDialog)
    PumpAndRotationDialog.show()
    sys.exit(app.exec_())
