# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\MicroscopeSelectDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MicroscopeSelectDialog(object):
    def setupUi(self, MicroscopeSelectDialog):
        MicroscopeSelectDialog.setObjectName("MicroscopeSelectDialog")
        MicroscopeSelectDialog.resize(400, 179)
        self.microscope_select_label = QtWidgets.QLabel(MicroscopeSelectDialog)
        self.microscope_select_label.setGeometry(QtCore.QRect(80, -10, 251, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.microscope_select_label.setFont(font)
        self.microscope_select_label.setAlignment(QtCore.Qt.AlignCenter)
        self.microscope_select_label.setObjectName("microscope_select_label")
        self.microscope_combo_box = QtWidgets.QComboBox(MicroscopeSelectDialog)
        self.microscope_combo_box.setGeometry(QtCore.QRect(140, 60, 131, 22))
        self.microscope_combo_box.setObjectName("microscope_combo_box")
        self.confirm_button = QtWidgets.QPushButton(MicroscopeSelectDialog)
        self.confirm_button.setGeometry(QtCore.QRect(170, 90, 75, 23))
        self.confirm_button.setObjectName("confirm_button")

        self.retranslateUi(MicroscopeSelectDialog)
        QtCore.QMetaObject.connectSlotsByName(MicroscopeSelectDialog)

    def retranslateUi(self, MicroscopeSelectDialog):
        _translate = QtCore.QCoreApplication.translate
        MicroscopeSelectDialog.setWindowTitle(_translate("MicroscopeSelectDialog", "Dialog"))
        self.microscope_select_label.setText(_translate("MicroscopeSelectDialog", "Select Microscope"))
        self.confirm_button.setText(_translate("MicroscopeSelectDialog", "Confirm"))


class MicroscopeSelectDialog(QtWidgets.QDialog, Ui_MicroscopeSelectDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
