# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Raghu\Desktop\Microscope Software\LS_Pycro_App\LS_Pycro_App\htls_acquisition\views\ui\HTLSAcqDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HTLSAcqDialog(object):
    def setupUi(self, HTLSAcqDialog):
        HTLSAcqDialog.setObjectName("HTLSAcqDialog")
        HTLSAcqDialog.resize(430, 147)
        self.fish_label = QtWidgets.QLabel(HTLSAcqDialog)
        self.fish_label.setGeometry(QtCore.QRect(186, 0, 61, 20))
        self.fish_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fish_label.setObjectName("fish_label")
        self.region_label = QtWidgets.QLabel(HTLSAcqDialog)
        self.region_label.setGeometry(QtCore.QRect(180, 20, 71, 20))
        self.region_label.setAlignment(QtCore.Qt.AlignCenter)
        self.region_label.setObjectName("region_label")
        self.acq_label = QtWidgets.QLabel(HTLSAcqDialog)
        self.acq_label.setGeometry(QtCore.QRect(0, 30, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.acq_label.setFont(font)
        self.acq_label.setAlignment(QtCore.Qt.AlignCenter)
        self.acq_label.setObjectName("acq_label")
        self.abort_button = QtWidgets.QPushButton(HTLSAcqDialog)
        self.abort_button.setGeometry(QtCore.QRect(180, 110, 75, 23))
        self.abort_button.setObjectName("abort_button")

        self.retranslateUi(HTLSAcqDialog)
        QtCore.QMetaObject.connectSlotsByName(HTLSAcqDialog)

    def retranslateUi(self, HTLSAcqDialog):
        _translate = QtCore.QCoreApplication.translate
        HTLSAcqDialog.setWindowTitle(_translate("HTLSAcqDialog", "Acquisition"))
        self.fish_label.setText(_translate("HTLSAcqDialog", "Fish 1"))
        self.region_label.setText(_translate("HTLSAcqDialog", "Region 1"))
        self.acq_label.setText(_translate("HTLSAcqDialog", "No Acquisition Running"))
        self.abort_button.setWhatsThis(_translate("HTLSAcqDialog", "<html><head/><body><p>Opens up Abort Dialog to abort running acquisition</p></body></html>"))
        self.abort_button.setText(_translate("HTLSAcqDialog", "Abort"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HTLSAcqDialog = QtWidgets.QDialog()
    ui = Ui_HTLSAcqDialog()
    ui.setupUi(HTLSAcqDialog)
    HTLSAcqDialog.show()
    sys.exit(app.exec_())
