# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\marim\Desktop\LS_Pycro_App\LS_Pycro_App\views\ui\HTLSRegionsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


