# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\marim\Desktop\LS_Pycro_App\LS_Pycro_App\views\ui\HTLSMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HTLSMainWindow(object):
    def setupUi(self, HTLSMainWindow):
        HTLSMainWindow.setObjectName("HTLSMainWindow")
        HTLSMainWindow.resize(511, 263)
        self.centralwidget = QtWidgets.QWidget(HTLSMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.galvo_button = QtWidgets.QPushButton(self.centralwidget)
        self.galvo_button.setGeometry(QtCore.QRect(20, 90, 101, 31))
        self.galvo_button.setObjectName("galvo_button")
        self.lsfm_label = QtWidgets.QLabel(self.centralwidget)
        self.lsfm_label.setGeometry(QtCore.QRect(30, 0, 451, 61))
        self.lsfm_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lsfm_label.setObjectName("lsfm_label")
        self.regions_button = QtWidgets.QPushButton(self.centralwidget)
        self.regions_button.setGeometry(QtCore.QRect(370, 90, 111, 31))
        self.regions_button.setObjectName("regions_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(200, 180, 111, 31))
        self.exit_button.setObjectName("exit_button")
        self.rotation_and_pump_button = QtWidgets.QPushButton(self.centralwidget)
        self.rotation_and_pump_button.setGeometry(QtCore.QRect(180, 92, 141, 31))
        self.rotation_and_pump_button.setObjectName("rotation_and_pump_button")
        HTLSMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HTLSMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 511, 26))
        self.menubar.setObjectName("menubar")
        HTLSMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HTLSMainWindow)
        self.statusbar.setObjectName("statusbar")
        HTLSMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HTLSMainWindow)
        QtCore.QMetaObject.connectSlotsByName(HTLSMainWindow)

    def retranslateUi(self, HTLSMainWindow):
        _translate = QtCore.QCoreApplication.translate
        HTLSMainWindow.setWindowTitle(_translate("HTLSMainWindow", "Main Window"))
        self.galvo_button.setText(_translate("HTLSMainWindow", "Galvo Setup"))
        self.lsfm_label.setText(_translate("HTLSMainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">HTLS LSFM Control Software</span></p></body></html>"))
        self.regions_button.setText(_translate("HTLSMainWindow", "Regions Setup"))
        self.exit_button.setText(_translate("HTLSMainWindow", "Exit"))
        self.rotation_and_pump_button.setWhatsThis(_translate("HTLSMainWindow", "<html><head/><body><p>Shows the Acquisition Settings Dialog for additional acquisition settings and to start acquisition.</p></body></html>"))
        self.rotation_and_pump_button.setText(_translate("HTLSMainWindow", "Rotation/Pump Control"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HTLSMainWindow = QtWidgets.QMainWindow()
    ui = Ui_HTLSMainWindow()
    ui.setupUi(HTLSMainWindow)
    HTLSMainWindow.show()
    sys.exit(app.exec_())
